// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: odrpc/rpc.proto

package odrpc

import (
	bytes "bytes"
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type GetDetectorsResponse struct {
	Detectors []*Detector `protobuf:"bytes,1,rep,name=detectors,proto3" json:"detectors,omitempty"`
}

func (m *GetDetectorsResponse) Reset()      { *m = GetDetectorsResponse{} }
func (*GetDetectorsResponse) ProtoMessage() {}
func (*GetDetectorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edafdb9f55df517e, []int{0}
}
func (m *GetDetectorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetDetectorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetDetectorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetDetectorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDetectorsResponse.Merge(m, src)
}
func (m *GetDetectorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetDetectorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDetectorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDetectorsResponse proto.InternalMessageInfo

func (m *GetDetectorsResponse) GetDetectors() []*Detector {
	if m != nil {
		return m.Detectors
	}
	return nil
}

type Detector struct {
	// The name for this config
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The name for this config
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Model Name
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Labels
	Labels []string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	// The detection width
	Width int32 `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	// The detection height
	Height int32 `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	// The detection channels
	Channels int32 `protobuf:"varint,7,opt,name=channels,proto3" json:"channels,omitempty"`
}

func (m *Detector) Reset()      { *m = Detector{} }
func (*Detector) ProtoMessage() {}
func (*Detector) Descriptor() ([]byte, []int) {
	return fileDescriptor_edafdb9f55df517e, []int{1}
}
func (m *Detector) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Detector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Detector.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Detector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detector.Merge(m, src)
}
func (m *Detector) XXX_Size() int {
	return m.Size()
}
func (m *Detector) XXX_DiscardUnknown() {
	xxx_messageInfo_Detector.DiscardUnknown(m)
}

var xxx_messageInfo_Detector proto.InternalMessageInfo

func (m *Detector) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Detector) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Detector) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Detector) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Detector) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Detector) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Detector) GetChannels() int32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

// The Process Request
type DetectRequest struct {
	// The ID for the request.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The ID for the request.
	DetectorName string `protobuf:"bytes,2,opt,name=detector_name,json=detectorName,proto3" json:"detector_name,omitempty"`
	// The image data
	Data Raw `protobuf:"bytes,3,opt,name=data,proto3,casttype=Raw" json:"data"`
	// What to detect
	Detect map[string]float32 `protobuf:"bytes,4,rep,name=detect,proto3" json:"detect,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
}

func (m *DetectRequest) Reset()      { *m = DetectRequest{} }
func (*DetectRequest) ProtoMessage() {}
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_edafdb9f55df517e, []int{2}
}
func (m *DetectRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DetectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DetectRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DetectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectRequest.Merge(m, src)
}
func (m *DetectRequest) XXX_Size() int {
	return m.Size()
}
func (m *DetectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectRequest proto.InternalMessageInfo

func (m *DetectRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetectRequest) GetDetectorName() string {
	if m != nil {
		return m.DetectorName
	}
	return ""
}

func (m *DetectRequest) GetData() Raw {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DetectRequest) GetDetect() map[string]float32 {
	if m != nil {
		return m.Detect
	}
	return nil
}

// Area for detection
type Detection struct {
	// Coordinates
	X1         int32   `protobuf:"varint,1,opt,name=x1,proto3" json:"x1"`
	Y1         int32   `protobuf:"varint,2,opt,name=y1,proto3" json:"y1"`
	X2         int32   `protobuf:"varint,3,opt,name=x2,proto3" json:"x2"`
	Y2         int32   `protobuf:"varint,4,opt,name=y2,proto3" json:"y2"`
	Label      string  `protobuf:"bytes,5,opt,name=label,proto3" json:"label"`
	Confidence float32 `protobuf:"fixed32,6,opt,name=confidence,proto3" json:"confidence"`
}

func (m *Detection) Reset()      { *m = Detection{} }
func (*Detection) ProtoMessage() {}
func (*Detection) Descriptor() ([]byte, []int) {
	return fileDescriptor_edafdb9f55df517e, []int{3}
}
func (m *Detection) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Detection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Detection.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Detection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detection.Merge(m, src)
}
func (m *Detection) XXX_Size() int {
	return m.Size()
}
func (m *Detection) XXX_DiscardUnknown() {
	xxx_messageInfo_Detection.DiscardUnknown(m)
}

var xxx_messageInfo_Detection proto.InternalMessageInfo

func (m *Detection) GetX1() int32 {
	if m != nil {
		return m.X1
	}
	return 0
}

func (m *Detection) GetY1() int32 {
	if m != nil {
		return m.Y1
	}
	return 0
}

func (m *Detection) GetX2() int32 {
	if m != nil {
		return m.X2
	}
	return 0
}

func (m *Detection) GetY2() int32 {
	if m != nil {
		return m.Y2
	}
	return 0
}

func (m *Detection) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Detection) GetConfidence() float32 {
	if m != nil {
		return m.Confidence
	}
	return 0
}

type DetectResponse struct {
	// The id for the response
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The detected areas
	Detections []*Detection `protobuf:"bytes,2,rep,name=detections,proto3" json:"detections,omitempty"`
	// If there was an error (streaming endpoint only)
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *DetectResponse) Reset()      { *m = DetectResponse{} }
func (*DetectResponse) ProtoMessage() {}
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_edafdb9f55df517e, []int{4}
}
func (m *DetectResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DetectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DetectResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DetectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectResponse.Merge(m, src)
}
func (m *DetectResponse) XXX_Size() int {
	return m.Size()
}
func (m *DetectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectResponse proto.InternalMessageInfo

func (m *DetectResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DetectResponse) GetDetections() []*Detection {
	if m != nil {
		return m.Detections
	}
	return nil
}

func (m *DetectResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetDetectorsResponse)(nil), "odrpc.GetDetectorsResponse")
	proto.RegisterType((*Detector)(nil), "odrpc.Detector")
	proto.RegisterType((*DetectRequest)(nil), "odrpc.DetectRequest")
	proto.RegisterMapType((map[string]float32)(nil), "odrpc.DetectRequest.DetectEntry")
	proto.RegisterType((*Detection)(nil), "odrpc.Detection")
	proto.RegisterType((*DetectResponse)(nil), "odrpc.DetectResponse")
}

func init() { proto.RegisterFile("odrpc/rpc.proto", fileDescriptor_edafdb9f55df517e) }

var fileDescriptor_edafdb9f55df517e = []byte{
	// 699 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x3d, 0x6f, 0xd3, 0x40,
	0x18, 0xce, 0x5d, 0x3e, 0xda, 0x5c, 0xd3, 0x0f, 0x9d, 0x4a, 0xb1, 0xd2, 0xca, 0x89, 0xdc, 0x25,
	0xaa, 0x54, 0xbb, 0x31, 0x4b, 0xe9, 0x46, 0x44, 0xc5, 0xc6, 0x70, 0x08, 0x21, 0x75, 0x41, 0x8e,
	0x7d, 0x4d, 0x2c, 0x12, 0x9f, 0xb1, 0x2f, 0x34, 0x06, 0x21, 0x21, 0x66, 0x06, 0x24, 0xfe, 0x04,
	0xe2, 0x37, 0xf0, 0x03, 0x18, 0x2b, 0xb1, 0x74, 0x8a, 0xa8, 0xcb, 0x80, 0x32, 0x75, 0x66, 0x42,
	0xbe, 0x3b, 0xb7, 0x6e, 0xd5, 0x85, 0xc9, 0xef, 0xf3, 0xdc, 0x73, 0xef, 0xe7, 0xbd, 0x46, 0xab,
	0xcc, 0x8b, 0x42, 0xd7, 0x8a, 0x42, 0xd7, 0x0c, 0x23, 0xc6, 0x19, 0xae, 0x0a, 0xa2, 0xb9, 0x35,
	0x60, 0x6c, 0x30, 0xa2, 0x96, 0x13, 0xfa, 0x96, 0x13, 0x04, 0x8c, 0x3b, 0xdc, 0x67, 0x41, 0x2c,
	0x45, 0xcd, 0x4d, 0x75, 0x2a, 0x50, 0x7f, 0x72, 0x6c, 0xd1, 0x71, 0xc8, 0x13, 0x75, 0xb8, 0x3b,
	0xf0, 0xf9, 0x70, 0xd2, 0x37, 0x5d, 0x36, 0xb6, 0x06, 0x6c, 0xc0, 0xae, 0x55, 0x19, 0x12, 0x40,
	0x58, 0x52, 0x6e, 0x1c, 0xa2, 0xf5, 0x27, 0x94, 0x3f, 0xa6, 0x9c, 0xba, 0x9c, 0x45, 0x31, 0xa1,
	0x71, 0xc8, 0x82, 0x98, 0xe2, 0x5d, 0x54, 0xf7, 0x72, 0x52, 0x03, 0xed, 0x72, 0x67, 0xc9, 0x5e,
	0x35, 0x45, 0x72, 0x66, 0x2e, 0x26, 0xd7, 0x0a, 0xe3, 0x1b, 0x40, 0x8b, 0x39, 0x8f, 0x31, 0xaa,
	0x04, 0xce, 0x98, 0x6a, 0xa0, 0x0d, 0x3a, 0x75, 0x22, 0xec, 0x8c, 0xe3, 0x49, 0x48, 0x35, 0x28,
	0xb9, 0xcc, 0xc6, 0xeb, 0xa8, 0x3a, 0x66, 0x1e, 0x1d, 0x69, 0x65, 0x41, 0x4a, 0x80, 0x37, 0x50,
	0x6d, 0xe4, 0xf4, 0xe9, 0x28, 0xd6, 0x2a, 0xed, 0x72, 0xa7, 0x4e, 0x14, 0xca, 0xd4, 0x27, 0xbe,
	0xc7, 0x87, 0x5a, 0xb5, 0x0d, 0x3a, 0x55, 0x22, 0x41, 0xa6, 0x1e, 0x52, 0x7f, 0x30, 0xe4, 0x5a,
	0x4d, 0xd0, 0x0a, 0xe1, 0x26, 0x5a, 0x74, 0x87, 0x4e, 0x10, 0x64, 0x7e, 0x16, 0xc4, 0xc9, 0x15,
	0x36, 0x66, 0x00, 0x2d, 0xcb, 0x64, 0x09, 0x7d, 0x3d, 0xa1, 0x31, 0xc7, 0x2b, 0x08, 0xfa, 0x9e,
	0xca, 0x17, 0xfa, 0x1e, 0xde, 0x46, 0xcb, 0x79, 0x6d, 0x2f, 0x45, 0x29, 0x32, 0xed, 0x46, 0x4e,
	0x3e, 0xcd, 0x4a, 0xda, 0x46, 0x15, 0xcf, 0xe1, 0x8e, 0xc8, 0xbe, 0xd1, 0x5b, 0x9d, 0xcf, 0x5a,
	0x02, 0xff, 0x9d, 0xb5, 0xca, 0xc4, 0x39, 0x21, 0x02, 0xe0, 0x7d, 0x54, 0x93, 0x97, 0x44, 0x35,
	0x4b, 0x76, 0xfb, 0x46, 0x13, 0x55, 0x7c, 0x85, 0x0e, 0x03, 0x1e, 0x25, 0x44, 0xe9, 0x9b, 0x0f,
	0xd1, 0x52, 0x81, 0xc6, 0x6b, 0xa8, 0xfc, 0x8a, 0x26, 0x2a, 0xc7, 0xcc, 0xcc, 0x1a, 0xf2, 0xc6,
	0x19, 0x4d, 0x64, 0x72, 0x90, 0x48, 0x70, 0x00, 0xf7, 0x81, 0xf1, 0x1d, 0xa0, 0xba, 0xbc, 0xeb,
	0xb3, 0x00, 0x6f, 0x20, 0x38, 0xed, 0x8a, 0x8b, 0xd5, 0x5e, 0x6d, 0x3e, 0x6b, 0xc1, 0x69, 0x97,
	0xc0, 0x69, 0x37, 0xe3, 0x93, 0xae, 0xb8, 0xac, 0xf8, 0xa4, 0x4b, 0x60, 0x22, 0xf8, 0xa9, 0x2d,
	0xaa, 0xca, 0xf5, 0x36, 0x81, 0x53, 0x5b, 0xe8, 0x6d, 0xad, 0x52, 0xd0, 0xdb, 0x04, 0x26, 0x36,
	0x6e, 0xa1, 0xaa, 0x18, 0x91, 0x18, 0x4c, 0xbd, 0x57, 0x9f, 0xcf, 0x5a, 0x92, 0x20, 0xf2, 0x83,
	0x4d, 0x84, 0x5c, 0x16, 0x1c, 0xfb, 0x1e, 0x0d, 0x5c, 0x2a, 0xe6, 0x04, 0x7b, 0x2b, 0xf3, 0x59,
	0xab, 0xc0, 0x92, 0x82, 0x6d, 0x0c, 0xd1, 0x4a, 0xde, 0x1e, 0xf5, 0x1a, 0x6f, 0xcf, 0x67, 0x0f,
	0x21, 0x2f, 0xaf, 0x2f, 0xd6, 0xa0, 0xe8, 0xec, 0xda, 0x8d, 0xce, 0xfa, 0x2c, 0x20, 0x05, 0x4d,
	0xd6, 0x2c, 0x1a, 0x45, 0x2c, 0xca, 0xdf, 0x9a, 0x00, 0xf6, 0x27, 0x88, 0xe4, 0xc6, 0xe1, 0x17,
	0xa8, 0x51, 0xdc, 0x03, 0xbc, 0x61, 0xca, 0x25, 0x33, 0xf3, 0xf5, 0x31, 0x0f, 0xb3, 0x25, 0x6b,
	0x6e, 0xaa, 0x28, 0x77, 0x2d, 0x8d, 0x81, 0x3f, 0xfe, 0xfc, 0xfd, 0x05, 0x36, 0x30, 0xb2, 0xae,
	0x36, 0x03, 0x0f, 0x50, 0x4d, 0x0a, 0xf1, 0xfa, 0x5d, 0xa3, 0x6f, 0xde, 0xbb, 0xc5, 0x2a, 0x57,
	0x7b, 0xc2, 0xd5, 0x8e, 0xb1, 0xa0, 0x5c, 0x1d, 0x80, 0x9d, 0xa3, 0x2d, 0xe3, 0xbe, 0x42, 0xd6,
	0xbb, 0x1b, 0xcf, 0xf3, 0xfd, 0x01, 0xd8, 0xc1, 0x8f, 0x50, 0x43, 0xfa, 0x78, 0xc6, 0x23, 0xea,
	0x8c, 0xff, 0x2f, 0x5c, 0xa9, 0x03, 0xf6, 0x40, 0xef, 0xf9, 0xe9, 0xb9, 0x5e, 0x3a, 0x3b, 0xd7,
	0x4b, 0x97, 0xe7, 0x3a, 0xf8, 0x90, 0xea, 0xe0, 0x6b, 0xaa, 0x83, 0x1f, 0xa9, 0x0e, 0x4e, 0x53,
	0x1d, 0xfc, 0x4a, 0x75, 0xf0, 0x27, 0xd5, 0x4b, 0x97, 0xa9, 0x0e, 0x3e, 0x5f, 0xe8, 0xa5, 0xd3,
	0x0b, 0xbd, 0x74, 0x76, 0xa1, 0x97, 0x8e, 0x5a, 0x85, 0x3f, 0x4e, 0x1c, 0xb0, 0x93, 0xb7, 0x8e,
	0x3b, 0xb4, 0x3c, 0xc6, 0xbc, 0xd8, 0x12, 0xb1, 0xfa, 0x35, 0xd1, 0xc3, 0x07, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x84, 0x9f, 0x9d, 0x30, 0xee, 0x04, 0x00, 0x00,
}

func (this *GetDetectorsResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetDetectorsResponse)
	if !ok {
		that2, ok := that.(GetDetectorsResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Detectors) != len(that1.Detectors) {
		return false
	}
	for i := range this.Detectors {
		if !this.Detectors[i].Equal(that1.Detectors[i]) {
			return false
		}
	}
	return true
}
func (this *Detector) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Detector)
	if !ok {
		that2, ok := that.(Detector)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if this.Model != that1.Model {
		return false
	}
	if len(this.Labels) != len(that1.Labels) {
		return false
	}
	for i := range this.Labels {
		if this.Labels[i] != that1.Labels[i] {
			return false
		}
	}
	if this.Width != that1.Width {
		return false
	}
	if this.Height != that1.Height {
		return false
	}
	if this.Channels != that1.Channels {
		return false
	}
	return true
}
func (this *DetectRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectRequest)
	if !ok {
		that2, ok := that.(DetectRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.DetectorName != that1.DetectorName {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	if len(this.Detect) != len(that1.Detect) {
		return false
	}
	for i := range this.Detect {
		if this.Detect[i] != that1.Detect[i] {
			return false
		}
	}
	return true
}
func (this *Detection) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Detection)
	if !ok {
		that2, ok := that.(Detection)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.X1 != that1.X1 {
		return false
	}
	if this.Y1 != that1.Y1 {
		return false
	}
	if this.X2 != that1.X2 {
		return false
	}
	if this.Y2 != that1.Y2 {
		return false
	}
	if this.Label != that1.Label {
		return false
	}
	if this.Confidence != that1.Confidence {
		return false
	}
	return true
}
func (this *DetectResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DetectResponse)
	if !ok {
		that2, ok := that.(DetectResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if len(this.Detections) != len(that1.Detections) {
		return false
	}
	for i := range this.Detections {
		if !this.Detections[i].Equal(that1.Detections[i]) {
			return false
		}
	}
	if this.Error != that1.Error {
		return false
	}
	return true
}
func (this *GetDetectorsResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&odrpc.GetDetectorsResponse{")
	if this.Detectors != nil {
		s = append(s, "Detectors: "+fmt.Sprintf("%#v", this.Detectors)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Detector) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 11)
	s = append(s, "&odrpc.Detector{")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	s = append(s, "Model: "+fmt.Sprintf("%#v", this.Model)+",\n")
	s = append(s, "Labels: "+fmt.Sprintf("%#v", this.Labels)+",\n")
	s = append(s, "Width: "+fmt.Sprintf("%#v", this.Width)+",\n")
	s = append(s, "Height: "+fmt.Sprintf("%#v", this.Height)+",\n")
	s = append(s, "Channels: "+fmt.Sprintf("%#v", this.Channels)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DetectRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&odrpc.DetectRequest{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "DetectorName: "+fmt.Sprintf("%#v", this.DetectorName)+",\n")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	keysForDetect := make([]string, 0, len(this.Detect))
	for k, _ := range this.Detect {
		keysForDetect = append(keysForDetect, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForDetect)
	mapStringForDetect := "map[string]float32{"
	for _, k := range keysForDetect {
		mapStringForDetect += fmt.Sprintf("%#v: %#v,", k, this.Detect[k])
	}
	mapStringForDetect += "}"
	if this.Detect != nil {
		s = append(s, "Detect: "+mapStringForDetect+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Detection) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&odrpc.Detection{")
	s = append(s, "X1: "+fmt.Sprintf("%#v", this.X1)+",\n")
	s = append(s, "Y1: "+fmt.Sprintf("%#v", this.Y1)+",\n")
	s = append(s, "X2: "+fmt.Sprintf("%#v", this.X2)+",\n")
	s = append(s, "Y2: "+fmt.Sprintf("%#v", this.Y2)+",\n")
	s = append(s, "Label: "+fmt.Sprintf("%#v", this.Label)+",\n")
	s = append(s, "Confidence: "+fmt.Sprintf("%#v", this.Confidence)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DetectResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&odrpc.DetectResponse{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	if this.Detections != nil {
		s = append(s, "Detections: "+fmt.Sprintf("%#v", this.Detections)+",\n")
	}
	s = append(s, "Error: "+fmt.Sprintf("%#v", this.Error)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringRpc(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OdrpcClient is the client API for Odrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OdrpcClient interface {
	// Get Config
	GetDetectors(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDetectorsResponse, error)
	// Process an request
	Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error)
	// Process stream requests
	DetectStream(ctx context.Context, opts ...grpc.CallOption) (Odrpc_DetectStreamClient, error)
}

type odrpcClient struct {
	cc *grpc.ClientConn
}

func NewOdrpcClient(cc *grpc.ClientConn) OdrpcClient {
	return &odrpcClient{cc}
}

func (c *odrpcClient) GetDetectors(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetDetectorsResponse, error) {
	out := new(GetDetectorsResponse)
	err := c.cc.Invoke(ctx, "/odrpc.odrpc/GetDetectors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *odrpcClient) Detect(ctx context.Context, in *DetectRequest, opts ...grpc.CallOption) (*DetectResponse, error) {
	out := new(DetectResponse)
	err := c.cc.Invoke(ctx, "/odrpc.odrpc/Detect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *odrpcClient) DetectStream(ctx context.Context, opts ...grpc.CallOption) (Odrpc_DetectStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Odrpc_serviceDesc.Streams[0], "/odrpc.odrpc/DetectStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &odrpcDetectStreamClient{stream}
	return x, nil
}

type Odrpc_DetectStreamClient interface {
	Send(*DetectRequest) error
	Recv() (*DetectResponse, error)
	grpc.ClientStream
}

type odrpcDetectStreamClient struct {
	grpc.ClientStream
}

func (x *odrpcDetectStreamClient) Send(m *DetectRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *odrpcDetectStreamClient) Recv() (*DetectResponse, error) {
	m := new(DetectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OdrpcServer is the server API for Odrpc service.
type OdrpcServer interface {
	// Get Config
	GetDetectors(context.Context, *empty.Empty) (*GetDetectorsResponse, error)
	// Process an request
	Detect(context.Context, *DetectRequest) (*DetectResponse, error)
	// Process stream requests
	DetectStream(Odrpc_DetectStreamServer) error
}

func RegisterOdrpcServer(s *grpc.Server, srv OdrpcServer) {
	s.RegisterService(&_Odrpc_serviceDesc, srv)
}

func _Odrpc_GetDetectors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OdrpcServer).GetDetectors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odrpc.odrpc/GetDetectors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OdrpcServer).GetDetectors(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odrpc_Detect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OdrpcServer).Detect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odrpc.odrpc/Detect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OdrpcServer).Detect(ctx, req.(*DetectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Odrpc_DetectStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OdrpcServer).DetectStream(&odrpcDetectStreamServer{stream})
}

type Odrpc_DetectStreamServer interface {
	Send(*DetectResponse) error
	Recv() (*DetectRequest, error)
	grpc.ServerStream
}

type odrpcDetectStreamServer struct {
	grpc.ServerStream
}

func (x *odrpcDetectStreamServer) Send(m *DetectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *odrpcDetectStreamServer) Recv() (*DetectRequest, error) {
	m := new(DetectRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Odrpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "odrpc.odrpc",
	HandlerType: (*OdrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDetectors",
			Handler:    _Odrpc_GetDetectors_Handler,
		},
		{
			MethodName: "Detect",
			Handler:    _Odrpc_Detect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectStream",
			Handler:       _Odrpc_DetectStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "odrpc/rpc.proto",
}

func (m *GetDetectorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetDetectorsResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Detectors) > 0 {
		for _, msg := range m.Detectors {
			dAtA[i] = 0xa
			i++
			i = encodeVarintRpc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Detector) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Detector) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Type) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Type)))
		i += copy(dAtA[i:], m.Type)
	}
	if len(m.Model) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Model)))
		i += copy(dAtA[i:], m.Model)
	}
	if len(m.Labels) > 0 {
		for _, s := range m.Labels {
			dAtA[i] = 0x22
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	if m.Width != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.Width))
	}
	if m.Height != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.Height))
	}
	if m.Channels != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.Channels))
	}
	return i, nil
}

func (m *DetectRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DetectRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.DetectorName) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.DetectorName)))
		i += copy(dAtA[i:], m.DetectorName)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if len(m.Detect) > 0 {
		for k, _ := range m.Detect {
			dAtA[i] = 0x22
			i++
			v := m.Detect[k]
			mapSize := 1 + len(k) + sovRpc(uint64(len(k))) + 1 + 4
			i = encodeVarintRpc(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintRpc(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x15
			i++
			encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(v))))
			i += 4
		}
	}
	return i, nil
}

func (m *Detection) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Detection) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.X1 != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.X1))
	}
	if m.Y1 != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.Y1))
	}
	if m.X2 != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.X2))
	}
	if m.Y2 != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintRpc(dAtA, i, uint64(m.Y2))
	}
	if len(m.Label) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Label)))
		i += copy(dAtA[i:], m.Label)
	}
	if m.Confidence != 0 {
		dAtA[i] = 0x35
		i++
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Confidence))))
		i += 4
	}
	return i, nil
}

func (m *DetectResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DetectResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Detections) > 0 {
		for _, msg := range m.Detections {
			dAtA[i] = 0x12
			i++
			i = encodeVarintRpc(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Error) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintRpc(dAtA, i, uint64(len(m.Error)))
		i += copy(dAtA[i:], m.Error)
	}
	return i, nil
}

func encodeVarintRpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *GetDetectorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Detectors) > 0 {
		for _, e := range m.Detectors {
			l = e.Size()
			n += 1 + l + sovRpc(uint64(l))
		}
	}
	return n
}

func (m *Detector) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = len(m.Type)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = len(m.Model)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	if len(m.Labels) > 0 {
		for _, s := range m.Labels {
			l = len(s)
			n += 1 + l + sovRpc(uint64(l))
		}
	}
	if m.Width != 0 {
		n += 1 + sovRpc(uint64(m.Width))
	}
	if m.Height != 0 {
		n += 1 + sovRpc(uint64(m.Height))
	}
	if m.Channels != 0 {
		n += 1 + sovRpc(uint64(m.Channels))
	}
	return n
}

func (m *DetectRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = len(m.DetectorName)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	if len(m.Detect) > 0 {
		for k, v := range m.Detect {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovRpc(uint64(len(k))) + 1 + 4
			n += mapEntrySize + 1 + sovRpc(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *Detection) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.X1 != 0 {
		n += 1 + sovRpc(uint64(m.X1))
	}
	if m.Y1 != 0 {
		n += 1 + sovRpc(uint64(m.Y1))
	}
	if m.X2 != 0 {
		n += 1 + sovRpc(uint64(m.X2))
	}
	if m.Y2 != 0 {
		n += 1 + sovRpc(uint64(m.Y2))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	if m.Confidence != 0 {
		n += 5
	}
	return n
}

func (m *DetectResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	if len(m.Detections) > 0 {
		for _, e := range m.Detections {
			l = e.Size()
			n += 1 + l + sovRpc(uint64(l))
		}
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovRpc(uint64(l))
	}
	return n
}

func sovRpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRpc(x uint64) (n int) {
	return sovRpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *GetDetectorsResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetDetectorsResponse{`,
		`Detectors:` + strings.Replace(fmt.Sprintf("%v", this.Detectors), "Detector", "Detector", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Detector) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Detector{`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Model:` + fmt.Sprintf("%v", this.Model) + `,`,
		`Labels:` + fmt.Sprintf("%v", this.Labels) + `,`,
		`Width:` + fmt.Sprintf("%v", this.Width) + `,`,
		`Height:` + fmt.Sprintf("%v", this.Height) + `,`,
		`Channels:` + fmt.Sprintf("%v", this.Channels) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DetectRequest) String() string {
	if this == nil {
		return "nil"
	}
	keysForDetect := make([]string, 0, len(this.Detect))
	for k, _ := range this.Detect {
		keysForDetect = append(keysForDetect, k)
	}
	github_com_gogo_protobuf_sortkeys.Strings(keysForDetect)
	mapStringForDetect := "map[string]float32{"
	for _, k := range keysForDetect {
		mapStringForDetect += fmt.Sprintf("%v: %v,", k, this.Detect[k])
	}
	mapStringForDetect += "}"
	s := strings.Join([]string{`&DetectRequest{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`DetectorName:` + fmt.Sprintf("%v", this.DetectorName) + `,`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`Detect:` + mapStringForDetect + `,`,
		`}`,
	}, "")
	return s
}
func (this *Detection) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Detection{`,
		`X1:` + fmt.Sprintf("%v", this.X1) + `,`,
		`Y1:` + fmt.Sprintf("%v", this.Y1) + `,`,
		`X2:` + fmt.Sprintf("%v", this.X2) + `,`,
		`Y2:` + fmt.Sprintf("%v", this.Y2) + `,`,
		`Label:` + fmt.Sprintf("%v", this.Label) + `,`,
		`Confidence:` + fmt.Sprintf("%v", this.Confidence) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DetectResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DetectResponse{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`Detections:` + strings.Replace(fmt.Sprintf("%v", this.Detections), "Detection", "Detection", 1) + `,`,
		`Error:` + fmt.Sprintf("%v", this.Error) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringRpc(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *GetDetectorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetDetectorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetDetectorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Detectors", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Detectors = append(m.Detectors, &Detector{})
			if err := m.Detectors[len(m.Detectors)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Detector) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Detector: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Detector: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Model", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Model = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Labels", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Labels = append(m.Labels, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			m.Width = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Width |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Channels", wireType)
			}
			m.Channels = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Channels |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DetectRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DetectRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DetectRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DetectorName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DetectorName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Detect", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Detect == nil {
				m.Detect = make(map[string]float32)
			}
			var mapkey string
			var mapvalue float32
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowRpc
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowRpc
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthRpc
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthRpc
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapvaluetemp uint32
					if (iNdEx + 4) > l {
						return io.ErrUnexpectedEOF
					}
					mapvaluetemp = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
					iNdEx += 4
					mapvalue = math.Float32frombits(mapvaluetemp)
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipRpc(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthRpc
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Detect[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Detection) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Detection: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Detection: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X1", wireType)
			}
			m.X1 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X1 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y1", wireType)
			}
			m.Y1 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y1 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field X2", wireType)
			}
			m.X2 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.X2 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Y2", wireType)
			}
			m.Y2 = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Y2 |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Confidence", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Confidence = float32(math.Float32frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DetectResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DetectResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DetectResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Detections", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Detections = append(m.Detections, &Detection{})
			if err := m.Detections[len(m.Detections)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRpc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthRpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRpc
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthRpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthRpc
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRpc   = fmt.Errorf("proto: integer overflow")
)
